server:
  port: 8888

spring: 
  application:
    name: novare-service    
    
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

novare-service:
  page: 0
  size: 4

    

